### ISSUE TITLE
DLL: issue with push() method

### ISSUE THREAD

**Issue by CCallahanIV** [wenima/data-structures#36]
Only special case for push should be if len == 1. Is only time tail will need to be explicitly set from push.

Had problem with this method when I attempted to use DLL in another assignment.

Consider refactoring for simplicity - push should:
 - assign new head
 - assign old prev to new head
 - assign new head nxt to old head
 - if len == 1, head = tail

**Comment by wenima** [comment]
ok, let's discuss as I'm not clear what the issue is. You said you had "a problem". Was it not working i.e. had a bug or it's just not simplistic enough as the code seems to be doing exaclty what you describe above.

```
new_dll = Dbl_Linked_List()
new_dll.push(5)
new_dll.push(6)
```
results in:
<img width="286" alt="screen shot 2016-12-17 at 1 33 56 pm" src="https://cloud.githubusercontent.com/assets/22766301/21289919/e2a3f7e0-c45d-11e6-96c2-1b72a6c03850.png">

**Comment by wenima** [comment]
see comment here: we should change the code in push to mirror append as it's less complex:

https://github.com/wenima/data-structures/issues/37#issuecomment-267789902

**Comment by CCallahanIV** [comment]
Rewrote, single if/else statement.
